### PR TITLE
Poor man's HTML.

### PR DESCRIPTION
**Pull request by dkorolev**
@grixa @mzhurovich @sompylasar 

Do not merge -- just an example.

how it looks

how it looks 2

For the top cards demo cruncher, this "appearance" whould be more than perfect :-)

Thanks,
Dima

### CODE REVIEW

**Comment by sompylasar** [comment]
@dkorolev You've missed the `<body>...</body>` tag, and the closing `</html>` tag. The `<body>` should open right after the `</head>` has closed, and close at the end of the content, right before the closing `</html>`.

**Comment by sompylasar** [comment]
@dkorolev BTW, don't you want a touch of style on that table?.. 👙

**Comment by dkorolev** [comment]
:+1: c2e2449

Not interested in touching  👙

**Comment by sompylasar** [comment]
@dkorolev `\n` aren't needed (and sometimes harmful). I suggest omitting them, use `Inspect Element` for a nice tree-view output of the DOM (HTML document object model), not just `view-source:` -- you said you like Chrome extensions.

**Comment by dkorolev** [comment]
Can we just live with the way it is now?

**Comment by sompylasar** [comment]
@dkorolev Sure, you are free, as in **free**dom. 🆓

**Comment by dkorolev** [comment]
Right. Free. :beer:

**Pull request closed without merging**
